name: FlyGen
options:
  bundleIdPrefix: com.flygen
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  DEVELOPMENT_TEAM: ""
  SWIFT_VERSION: "5.9"

targets:
  FlyGen:
    type: application
    platform: iOS
    sources:
      - FlyGen
    settings:
      INFOPLIST_FILE: FlyGen/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.flygen.app
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      TARGETED_DEVICE_FAMILY: "1"
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
      CODE_SIGN_ENTITLEMENTS: FlyGen/FlyGen.entitlements
    entitlements:
      path: FlyGen/FlyGen.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.flygen.app
        com.apple.developer.icloud-services:
          - CloudKit
